#pragma once

#include "jmsf_dll_convention.h"

#if defined( NEHE_TUTORIAL_DLL_INTERFACE_INTERNAL )
	#define NEHE_TUTORIAL_DLL_INTERFACE JMSF_DLL_EXPORT_CONVENTION
#else
	#define NEHE_TUTORIAL_DLL_INTERFACE JMSF_DLL_IMPORT_CONVENTION
#endif
